const REQUEST_USER_DATA_SUCCESS = '@ma-defi-REQUEST_USER_DATA_SUCCESS';
const REQUEST_USER_DATA = '@ma-defi-REQUEST_USER_DATA';
const GET_USER_DATA_ERROR = '@ma-defi-RECEIVE_USER_DATA_ERROR';

export {
  REQUEST_USER_DATA_SUCCESS, REQUEST_USER_DATA, GET_USER_DATA_ERROR,
};
